name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: bug
type: "Bug"
projects: budanov-xrs/1
assignees: budanov-xrs
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Описание проблемы
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: false
  - type: textarea
    attributes:
      label: Шаги для воспроизведения
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
