name: Form Bug Report
description: File a bug report.
title: "[Bug] "
labels: bug
projects: Arion-Soft/17
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить это сообщение об ошибке!
  - type: textarea
    id: bug-description
    attributes:
      label: Описание проблемы
      description: Расскажи что произошло
      value: ''
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение
      description: Также расскажите нам, чего вы ожидали?
      value: ''
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Шаги для воспроизведения
      description: Шаги по воспроизведению поведения.
      placeholder: |
        1. Шаг 1...
        1. Шаг 2...
        1. Шаг 3...
        1. Шаг 4...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Соответствующий вывод журнала
      description: Пожалуйста, скопируйте и вставьте все соответствующие данные журнала. Они будут автоматически преобразованы в код.
      render: shell
